src/Practice.Web.Journey/Controllers/CarController.cs
using System.Web.Mvc;
using Practice.Web.Model;

namespace Practice.Web.Journey.Controllers
{
    public class CarController : Controller
    {
        //
        // GET: /Car/

        public ActionResult Index()
        {
            PopulateReferenceDataViewBag();
            return View();
        }

        #region Private

        private void PopulateReferenceDataViewBag()
        {
            PopulatePersonalDetailsReferenceData();
        }

        private void PopulatePersonalDetailsReferenceData()
        {
            ViewBag.TitleTypes = TitleGender.GetTitleTypes();
            ViewBag.DisplayTitles = TitleGender.GetDisplayTitles();
            ViewBag.MaritalStatusTypes = MaritalStatusGroup.GetMaritalTypes();
            ViewBag.DisplayMaritalStatus = MaritalStatusGroup.GetDisplayMaritalTypes();

        }

        #endregion
    }
}

src/Practice.Web.Journey/Controllers/RiskController.cs
using System.Web.Mvc;
using Practice.Web.Model;

namespace Practice.Web.Journey.Controllers
{
    public class RiskController : Controller
    {
        public ActionResult SavePersonalDetails(PersonDetails personDetails)
        {
            var risk = new Risk(personDetails) {PersonDetails = personDetails};
            return Json(new {status = "OK"});
        }

        //public ActionResult SaveRisk()
        //{
        //    throw new System.NotImplementedException();
        //}
    }
}

src/Practice.Web.Journey/Views/Shared/JavascriptsConstants.cshtml
<script type="text/javascript">
    var practice_journey = practice_journey || {};
    practice_journey.SavePersonalDetailsSaveActionUrl = '@Url.Action("SavePersonalDetails","Risk")';
    practice_journey.riskSaveActionUrl = '@Url.Action("SaveRisk","Risk")';
 </script>

src/Practice.Web.Journey/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/Scripts/libs")
        @Scripts.Render("~/Scripts/PJourneyJavaScripts")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Car")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody() 
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>
        @RenderSection("scripts", required: false)
        @Html.Partial("_LayoutFooter")
    </body>
</html>

src/Practice.Web.Journey/Views/Shared/_LayoutFooter.cshtml
@Html.Partial("JavascriptsConstants")

src/Practice.Web.Journey/Views/Shared/_SectionLayout.cshtml
<div>
    @RenderBody()
</div>